uid = nobody
gid = nogroup
use chroot = no
max connections = 4
pid file = /var/run/rsyncd.pid
log file = /var/log/rsyncd.log

[backups]
    path = /home/backup
    comment = Backup module
    read only = yes
