version: "3.9"

networks:
  ctf_net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "false"
      com.docker.network.bridge.name: "br-ctf-net"
    ipam:
      config:
        - subnet: 10.10.10.0/24
          gateway: 10.10.10.1

services:
  gw_hc:
    image: alpine:3.19
    container_name: ctf_gw_hc
    command: ["sleep", "infinity"]
    networks:
      ctf_net:
        ipv4_address: 10.10.10.1

  srv_emr_web:
    build: ./web-emr
    container_name: ctf_srv_emr_web
    networks:
      ctf_net:
        ipv4_address: 10.10.10.10
    environment:
      DB_HOST: "10.10.10.20"
      DB_USER: "emrAdmin"
      DB_PASS: "P@ssw0rd!"
      DB_NAME: "emr_db"
      FLAG_SQLI: "HC-CTF{MRN-2025-CTF-01}"
      FLAG_XSS: "HC-CTF{XSS_EXECUTED}"
    # for local testing:
    # ports:
    #   - "8080:80"
    #   - "8443:443"

  srv_emr_db:
    build: ./db-emr
    container_name: ctf_srv_emr_db
    networks:
      ctf_net:
        ipv4_address: 10.10.10.20
    environment:
      MYSQL_ROOT_PASSWORD: "rootpass"
      MYSQL_DATABASE: "emr_db"
      MYSQL_USER: "emrAdmin"
      MYSQL_PASSWORD: "P@ssw0rd!"

  srv_filesmb:
    build: ./smb-file
    container_name: ctf_srv_filesmb
    networks:
      ctf_net:
        ipv4_address: 10.10.10.30

  srv_ftp_imaging:
    build: ./ftp-imaging
    container_name: ctf_srv_ftp_imaging
    networks:
      ctf_net:
        ipv4_address: 10.10.10.40

  srv_mail:
    build: ./mail-server
    container_name: ctf_srv_mail
    networks:
      ctf_net:
        ipv4_address: 10.10.10.50

  srv_backup:
    build: ./backup-host
    container_name: ctf_srv_backup
    networks:
      ctf_net:
        ipv4_address: 10.10.10.60

  client_mgmt:
    build: ./client-mgmt
    container_name: ctf_client_mgmt
    networks:
      ctf_net:
        ipv4_address: 10.10.10.70
    # for RDP testing locally:
    # ports:
    #   - "3389:3389"
