[global]
   workgroup = WORKGROUP
   server string = CTF SMB Server
   security = user
   map to guest = Bad User
   guest account = nobody
   server role = standalone server
   smb ports = 445
   disable netbios = no
   server min protocol = SMB2
   server max protocol = SMB3
   # Banner hints at older Samba build for CVE identification
   server string = Samba 4.5.16-Debian

[HR$]
   path = /srv/samba/hr
   browseable = no
   read only = yes
   guest ok = yes
