disable_plaintext_auth = no
log_path = /var/log/dovecot.log
protocols = imap pop3
mail_privileged_group = mail
mail_location = maildir:/mail/%u
ssl = no
first_valid_uid = 150

passdb {
  driver = passwd-file
  args = /etc/dovecot/dovecot.passwd
}

userdb {
  driver = static
  args = uid=vmail gid=mail home=/mail/%u
}

service imap-login {
  inet_listener imap {
    port = 143
  }
}

service pop3-login {
  inet_listener pop3 {
    port = 110
  }
}
