listen=YES
listen_ipv6=NO
anonymous_enable=YES
local_enable=NO
write_enable=NO
anon_root=/srv/ftp
no_anon_password=YES
dirmessage_enable=YES
use_localtime=YES
xferlog_enable=YES
connect_from_port_20=YES
# Fake banner to nudge detection of CVE-2011-2523
ftpd_banner=vsftpd 2.3.4
banner_file=/etc/banner.txt
